"""empty message

Revision ID: 4fbb3878b2df
Revises: 6fd10fe0742f
Create Date: 2018-03-15 20:50:55.445597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fbb3878b2df'
down_revision = '6fd10fe0742f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_request_submitter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('date_submitted', sa.DateTime(), nullable=True),
    sa.Column('date_required', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.String(length=12), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('impact', sa.String(length=255), nullable=True),
    sa.Column('assumptions', sa.Text(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('change_request_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('name')
    )
    op.create_table('change_request_types_change_request_submitters',
    sa.Column('crt_id', sa.Integer(), nullable=True),
    sa.Column('crs_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['crs_id'], ['change_request_submitter.id'], ),
    sa.ForeignKeyConstraint(['crt_id'], ['change_request_type.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('change_request_types_change_request_submitters')
    op.drop_table('change_request_type')
    op.drop_table('change_request_submitter')
    # ### end Alembic commands ###
